# postgresql-helm-argo-application.yml
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: argocd
spec:
  destination:
    namespace: minio
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/viethqb/argocd-vault-demo.git
    path: minio
    targetRevision: main
    plugin:
      name: argocd-vault-plugin-helm
      env:
        - name: HELM_VALUES
          value: |
            auth:
              rootUser: <path:kv-v2/data/lakehouse/minio#user>
              rootPassword: <path:kv-v2/data/lakehouse/minio#password>
            ingress:
              enabled: false
              ingressClassName: "nginx"
              hostname: minio.lakehouse.local
              annotations:
                nginx.ingress.kubernetes.io/proxy-body-size: 1024m
            defaultBuckets: "lakehouse, airflow, risingwave"
            persistence:
              size: 50Gi
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
