auth:
  rootUser: <path:kv-v2/data/argocd#admin>
  rootPassword: <path:kv-v2/data/argocd#password>
ingress:
  enabled: true
  ingressClassName: "nginx"
  hostname: minio.lakehouse.local
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 1024m
defaultBuckets: "lakehouse, airflow, risingwave"
persistence:
  size: 50Gi
